### PR TITLE
Add update subcommand

### PR DESCRIPTION
**Pull request by mhfowler**
So I kind of followed the airline model here to save yourself before you save other, 

it might end up not being necessary, 
but I imagined some kind of future situation where we need to run some type of data migration, before updating everything, 
and I imagined this pattern could allow for that. 

edit to make this more clear:
by "this pattern", I mean:
when you call peach-config update
- peach-config updates itself, and then it updates the other microservices

But in the immediate future, its probably wont really be used. 

In any event though, from the user perspective, or perspective of other microservices (aka peach-web) the interface is the same

`peach-config update`

nice and simple, basically just a wrapper for apt-get ... but extensible when we need

maybe we can start with this, and then in the future decide what type of information peach-web specifically needs back from the update?

### CODE REVIEW

**Comment by mhfowler** [comment]
I've tested this on the pi and its working

**Comment by mhfowler** [comment]
Assuming we only publish functional packages to Freight, 
using `peach-config update` on your pi to make sure you get the latest working code, 
also sounds so nice from a developer perspective, 
just simple process,
being like "ok" lets get the latest

**Comment by mhfowler** [comment]
Also will include this link here https://hub.mender.io/t/when-to-use-mender-vs-apt-get-update/3317 to the question I asked on the mender forum. 
So nice that people are helpful on the internet! I find their answer assuring that apt-get is actually a good fit for our use case for now.

**Review by mycognosist — APPROVED** [review]

**Comment by mycognosist** [comment]
> maybe we can start with this, and then in the future decide what type of information peach-web specifically needs back from the update?

Yeah this sounds good to me. I think we have a solid base to extend and adapt as the need arises.

**Pull request merged**
