### PR TITLE
No-user-input version of peach-config (for vmdb2)

### PR DESCRIPTION
**Pull request by mhfowler**
still need to clean this up

### CODE REVIEW

**Comment by mhfowler** [comment]
To run setup_dev_env.py within vmdb2, 
we need it to be able to run without user input.

I've adjusted a couple apt commands to use `-y` so they don't need user input. 

I still need to figure out:
- how to generate main peach user without a prompt for password (what should the default password be and how to set it?)
- how do do configure locales without user-input

**Comment by mycognosist** [comment]
@mhfowler 

> how to generate main peach user without a prompt for password (what should the default password be and how to set it?)

One option would be to use the `newusers` command: "The newusers command reads a file (or the standard input by default) and uses this information to update a set of existing users or to create new users." (Found on [this thread](https://unix.stackexchange.com/questions/21022/how-should-i-add-users-non-interactively)).

Regarding default password for the `peach` user, maybe `peach` or `cloud` ? Or `peachcloud` ? This reminds me that we'll need to add password-changing functionality to the web interface.

> how do do configure locales without user-input

Here's a thread on setting locales non-interactively: [How do you set a locale non-interactively on Debian/Ubuntu?](https://serverfault.com/questions/362903/how-do-you-set-a-locale-non-interactively-on-debian-ubuntu)

**Comment by mhfowler** [comment]
Based on [this SO answer](https://stackoverflow.com/questions/3190955/how-to-create-a-user-in-linux-using-python), I changed the non-interactive user creation to use "crypt" module and "useradd" bash command.  This seems like a pretty straightforward way to do this, what do you think? I have the initial password set as peachcloud now. 

For the user locale, 
perhaps should we not set the user local for the peach disc image, 
since we don't know what locale the user will be in?

maybe setting the locale could be something that happens through peach-web?

**Comment by mycognosist** [comment]
So it looks like there's a `None` option which can be selected as the default setting for locales ([Locale wiki](https://wiki.debian.org/Locale#Standard)), although there are some reports that this results in errors from `apt` and other programs ([SO post](https://raspberrypi.stackexchange.com/a/92705)).

We could try the `None` option and test it ourselves to see if we encounter any errors. Or we could go with a relatively safe and tested option and set the default as `en_US.UTF-8`.

**Comment by mhfowler** [comment]
@mycognosist the small moments of encountering US imperialism in tools available. hmm I can't really think of how None would be a better default than en_US.UTF-8, and sounds like it may have some downsides. Based on your response above it sounds like you are ok with either option, so I'll set it to en_US.UTF-8 for now, and we can put setting the locale on peach-web startup or through the interface in the todo list.

**Comment by mhfowler** [comment]
@mycognosist I've tested this by building the img and flashing it to the pi, and its working, 
confirmed peach user with default password and locale was set

-- can I merge this?

**Comment by mycognosist** [comment]
@mhfowler 

Rad. I really like how streamlined everything is now. It's great that you've included some flexibility with the optional arguments. Merge at will.

**Pull request merged**
