### PR TITLE
Add script to auto deploy AP

### PR DESCRIPTION
**Pull request by mycognosist**
Adds a script which starts the `ap0` service (access point) if the `wlan0` service is active but not connected to any access point. This offers a handy way to automatically start the access point if no `wlan0` connections are available. For example, the script can be run as a `systemd` service every `x` minutes.

An RPC already exists for this functionality in `peach-network`: `check_iface()`.

### CODE REVIEW

**Comment by mycognosist** [comment]
I've added `systemd` assets (service file and timer file) to control the repeated execution of the `ap_auto_deploy` script. Right now it's set to run 60 seconds after boot and once every 180 seconds after that. I think this could prove very useful (without a major trade-off), especially in a scenario where the `peach` is running locally in headless mode and the usual connection `wlan` connection goes down for some reason (maybe the access point gets unplugged or hit by a micrometeorite or something). With the 180 second cycle, there shouldn't ever be a major break in time before the AP becomes available. We can also tweak this in the future.

**Comment by mycognosist** [comment]
I've added configuration of this update to `setup_networking.py`. It copies the script, service file and timer file into place and then enabled and starts the timer.

**Comment by mhfowler** [comment]
@mycognosist a couple situations where I wonder how this would go:

- with this setup, is it true that if your router/wifi goes down for 10 minutes (or longer than 1 minute), then your peach will switch to access point mode? and won't switch back to wlan mode when the wifi goes back on
- related to above, if this is true, I could imagine a situation where this becomes frustrating, where wlan goes down sometimes and it ends up switching to access point mode in the background when you don't really want it to

**Comment by mycognosist** [comment]
@mhfowler 

> is it true that if your router/wifi goes down for 10 minutes (or longer than 180 seconds), then your peach will switch to access point mode? and won't switch back to wlan mode when the wifi goes back on

Yes, your understanding is correct. Hmm...I hear what you're saying about the possible annoyance and frustration. I suppose this is one of the great features of the physical interface (for example, being able to deploy the AP if your WiFi went down).

How about if we add the service and script but leave it disabled for now? Then we can always add a configuration setting in the web interface to enable the service if desired. Something like this:

[ ] - Automatically deploy access point when WiFi connection is unavailable

How does that sound?

**Comment by mhfowler** [comment]
@mycognosist I think that sounds good, and agreed being able to use the physical interface to switch to AP mode sounds like an incredibly useful feature and fallback for when the wifi goes down

**Pull request merged**
